Server/aspnetmvc5/aspnetmvc5/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace aspnetmvc5.Controllers
{
    public class DemoController : Controller
    {
        // GET: Demo
        public ActionResult Mvc()
        {
            return View();
        }

        public ActionResult WebApi()
        {
            return View();
        }

        public ActionResult HttpClient()
        {
            return View();
        }
    }
}

Server/aspnetmvc5/aspnetmvc5/Controllers/WebApiController.cs
using System.Collections.Generic;
using System.Web.Http;

namespace aspnetmvc5.Controllers
{
    public class WebApiController : ApiController
    {
        // GET api/WebApi
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/WebApi/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/WebApi
        public void Post([FromBody]string value)
        {
        }

        // PUT api/WebApi/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/WebApi/5
        public void Delete(int id)
        {
        }
    }
}

Server/aspnetmvc5/aspnetmvc5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Mvc", "Mvc", "Demo", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("WebAPI", "WebApi", "Demo", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("HttpClient", "HttpClient", "Demo", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>